# MetsTools addon for Blender
# Copyright (C) 2019 Mets 3D
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Useless text
	# Operators in this script:

	# Make Physics Bones
	#	Sets up a somewhat iffy physics rig on a string of selected pose bones. (aka video game style physics) Careful when using this, it does a lot of stuff.

	# Bake Auto Smooth
	#	Edges that are sharp because of Auto Smooth are marked as sharp. Works on entire selection of objects.

	# Create LightMap UVs
	#	If an object has exactly 1 UV channel, this creates a 2nd one using Smart UV Unwrap. Works on entire selection of objects. You can tweak the settings of the projection. Great for quickly creating lightmaps for game engines that tend to be better than the ones generated by the engine on import.

	# Clean Up Blend
	#	Massively automatized house keeping stuff. Has dozens of checkboxes, each describe what it does, see those tooltips to learn more. Works on entire selection of objects, or globally. Always works on all materials and other node trees globally.

	################################################
	# Todo
	#	UI
	#		Replace the "Remove unused vertex groups" addon's button that I found a long time ago with my own one.
	#	I'm not sure that my useless vertex group removal logic is correct right now - There are two separate calls to o.vertex_groups.remove(), when I think there should really only be one, and everything else should just be adding to safeVGroups.


	# Add these:
	#	CleanBioshockInfiniteImport
	#		Alternatively, could have one CleanUpImport operator with various sources as options.
	#	AutoSetupDirectXNormalMap - In the material editor, when a texture node is selected(expected that user will select normal map node) set datatype to non-color, create separateRGB, invert, combineRGB and normal map nodes, connect normal map node output to any BSDFs whose normal maps are currently unplugged.

	# Make these:
	#	Copy selected keyframes to selected bookmarks
	#	Rename shape key set names (key blocks)

	# Things marked with a * should be separate operators from the operator they are indented from.

	# Utilities
	#	MarkSharpByAutoSmooth (DONE)
	#	MakePhysicsBones (TODO, unstable, can be improved)
	#	CreateLightMapUVs (DONE)
	#	ConvertImages (TODO, convert to operator)
	#	ForceApplyMirrorModifier (TODO list inside, needs improvements for the mid-line)
	#	UnfuckSFMArmature - Could add more SFM clean-up related stuff. Best wait for Red Eye to improve his mdl importer though.
	
	# Copy Cloth Settings (or any modifier, idk)

	# Consistency toolset
	#	MakeModifiersConsistent (TODO, convert to operator)
	#	CleanUpBlend
	#		Done, could be put into separate operators:
	#			*Remove unused vertex groups - TODO: consider shape key masks
	#			Rename mesh datas
	#			Rename Single UV Maps
	#			Remove Blender Internal texture slots (May be reduntant in 2.8, and would probably throw errors)
	#			Fix Material Names (ending in .001) - Might need some improvement.
	#			Also try removing .001 from object names. (Probably check if an object without .001 exists, and if not, rename it)
	#			Clear Unused Nodes
	#			Hide node sockets: This thing is kindof useless imo and we should remove it.
	#			Center Nodes
	#			Fix Texture References
	#		Additions:
	#			Remove unused UV Maps(use code from Bioshock cleanup script)
	#			Clear Shape Key and Vertex Group search bars on all objects.
	#			Set Vertex Group value slider to 1.0 on all objects.
	#			Open or close or leave as it is: all bone constraints
	#			Open or close or leave as it is: all modifiers
	#			*Delete unused groups
	#			*Delete unused textures
	#			*Delete unused materials
	#			Relies on being able to enter edit mode on all objects(including hidden objects and objects on hidden layers):
	#				Unhide and deselect all in edit mode on all objects
	#				Seams from Islands
	#				Weight Normals (Add to my script, credit original author)
	#				Shade Smooth/Flat

	# Global toggles
	#	AutoSmooth On/Off
	#	Autosmooth angle
	#	UseAlpha
	#	ClothCache
	#	TextureNodesWidth

	##########################################################

bl_info = {
	"name": "MetsTools",
	"author": "Mets3D",
	"version": (2,3),
	"blender": (2, 80, 0),
	"location": "View3D > Search ",
	"description": "All kinds of tools",
	"category": "3D View"}
	
import bpy
from bpy.props import *
import bmesh
import mathutils
import math

from . import create_lightmap_uvs
from . import mark_sharp_by_autosmooth
from . import make_physics_bones
from . import cleanup_blend

def register():
	from bpy.utils import register_class

	create_lightmap_uvs.register()
	mark_sharp_by_autosmooth.register()
	make_physics_bones.register()
	cleanup_blend.register()
	
	#bpy.types.MESH_MT_shape_key_specials.append(draw_func_ApplyShapeKeyAsBase)
	#bpy.types.VIEW3D_MT_pose_specials.append(draw_func_MakePhysicsBones)
	#bpy.types.VIEW3D_MT_edit_mesh.append(draw_func_MarkSharpByAutoSmooth)
	#bpy.types.VIEW3D_MT_uv_map.append(draw_func_CreateLightMapUVs)

def unregister():
	from bpy.utils import unregister_class

	create_lightmap_uvs.unregister()
	mark_sharp_by_autosmooth.unregister()
	make_physics_bones.unregister()
	cleanup_blend.unregister()

	#unregister_class(CleanUpBlend)
	#unregister_class(MakePhysicsBones)
	
	#bpy.types.MESH_MT_shape_key_specials.remove(draw_func_ApplyShapeKeyAsBase)
	#bpy.types.VIEW3D_MT_pose_specials.remove(draw_func_MakePhysicsBones)
	#bpy.types.VIEW3D_MT_edit_mesh.remove(draw_func_MarkSharpByAutoSmooth)
	#bpy.types.VIEW3D_MT_uv_map.remove(draw_func_CreateLightMapUVs)